### ISSUE TITLE
Webpack is complaining about not being able to stat the build directory

### ISSUE THREAD

**Issue by cranberyxl** [masahirompp/aws-cdk-webpack-lambda-function#6]
Any ideas on this? If I make the dir ahead of time, there's no issue, but I don't think I should have to?

```ENOENT: no such file or directory, stat '/path/to/my/src/.build/91ab6e0cbf68bb050912bfa74de0d9c607e86930fc1685e4d90b08e21e445da9'```

**Comment by sdkitono** [comment]
Same error here as well how do we fix this?

**Comment by alexanderkagadovsky** [comment]
agree, I have the same error

**Comment by masahirompp** [comment]
@cranberyxl @sdkitono @alexanderkagadovsky I will work to fix this bug, but it will take some time.
please use aws-cdk-webpack-lambda-function@0.3.3.

**Comment by alexanderkagadovsky** [comment]
After digging into the problem I've a few issues:
* webpack doesn't build a lambda - there is no .build directory
I've fixed this locally using two steps: 
1) when initializing `new WebpackFunction` I set in props `buildDir: '.build'`
2) the webpack configuration is not altered correctly in https://github.com/masahirompp/aws-cdk-webpack-lambda-function/blob/master/lib/builder.ts#L30 . The code I have
```
    constructor(options) {
        const webpackConfig = require(options.config);
        webpackConfig.entry = options.entry;
        webpackConfig.output = {
            libraryTarget: "commonjs",
            path: options.output,
            hashFunction: "md4",
        };

        this.webpack = webpack(webpackConfig);
    }
``` 
(I've changed it in builder.js for debugging)
After these two steps it worked correctly and there was `.build` directory in the root folder
* However there is another problem in https://github.com/masahirompp/aws-cdk-webpack-lambda-function/blob/master/lib/builder.ts#L41
the code I have:
```
    build() {
        this.webpack.run((err, stats) => {
            if (stats.hasErrors()) {
                console.log(stats.toString());
            }
            console.log('does build exist: ', require('fs').existsSync(stats.outputOptions.path));

            if (err) {
                throw err;
            }
        });
    }
```

`err` doesn't have errors and errors can be found in `stats` (use debugger to check the variable value because its fails when using console.log)

The most important problem that the callback inside `this.webpack.run` finishes **after** when this code is executed https://github.com/masahirompp/aws-cdk-webpack-lambda-function/blob/master/lib/function.ts#L69 
```
export class WebpackSingletonFunction extends SingletonFunction {
  constructor(
    scope: Construct,
    id: string,
    props: WebpackSingletonFunctionProps
  ) {
    const { runtime, handlerDir, outputBasename, handler } = preProcess(props);

    super(scope, id, {
      ...props,
      runtime,
     **** code: Code.fromAsset(handlerDir),****
      handler: `${outputBasename}.${handler}`,
    });
  }
}
```

which results in that directory is not found. A seemingly logical solution might be to use a promise to wait till the build process is completed but this contradicts the CDK approach where everything is setup inside `constructor`.

@masahirompp for me the solution looks like the programmatical webpack compilation update should be rolled back as this implementation doesn't not comply with the CDK resources building ideology. Please let us know your thoughts.
I think it worked before because webpack-cli was used and presumably it blocked the process and was synchronously waiting till the compilation ends.

**Comment by reni11111** [comment]
any update?

**Comment by alexanderkagadovsky** [comment]
@reni11111 I wasn't able to fix this error. I configured webpack with CDK without using this library.

**Comment by masahirompp** [comment]
@reni11111 @alexanderkagadovsky sorry to reply late.
I've fixed it.
please use latest version. (aws-cdk-webpack-lambda-function@0.5.0)

**Comment by reni1111** [comment]
Thank you!
Very good work, you should apply for some funding at CDK, webpack is a must in every "cloud formation" platform.
Can you update the CDK dependencies to the last version too? (@aws-cdk/aws-lambda ...)

**Comment by masahirompp** [comment]
@reni1111 I update the CDK dependencies to the last version. please use latest version.
